// sveltekit/src/routes/results/g2/page-gpt.svelte
<script>
  let inputValue = '';

  function handleInput(event) {
    const regex = /^[0-9]*$/; // Regex to allow only numerical input
    if (regex.test(event.target.value)) {
      inputValue = event.target.value;
    }
  }

  function handleSubmit() {
    // Handle submit logic here
    console.log("Submitted:", inputValue);
  }
</script>

<div id="container" class="container">
  <input type="text" bind:value={inputValue} on:input={handleInput} placeholder="Enter numerical value" style="text-align: center;">
  <button on:click={handleSubmit}>Submit</button>
</div>

<style>
  .container {
    display: flex;
    justify-content: center;
    align-items: center;
    padding: 1rem;
    width: 100vw;
    height: 100vh;
  }

  input {
    padding: 0.5rem;
    border-radius: 5px;
    border: 1px solid #ccc;
    width: 200px;
  }

  button {
    padding: 0.5rem 1rem;
    margin-left: 1rem;
    border-radius: 5px;
    border: 1px solid #007bff;
    background-color: #007bff;
    color: #fff;
    cursor: pointer;
  }
</style>

// react/app/results/g2/page-gpt.tsx
import { useState } from 'react';

export default function G1() {
    const [value, setValue] = useState('');

    // Function to handle input change
    const handleChange = (event) => {
        const inputValue = event.target.value;
        // Check if the input value is numerical
        if (!isNaN(inputValue)) {
            // Update the state if it's numerical
            setValue(inputValue);
        }
    };

    // Function to handle submit
    const handleSubmit = () => {
        // Perform actions on submit
        console.log("Submitted value:", value);
    };

    return (
        <div id="container" className="flex justify-center items-center w-screen h-screen p-4">
            <input
                type="text"
                value={value}
                onChange={handleChange}
                className="p-2 border border-gray-300 rounded-md"
                placeholder="Enter a number"
            />
            <button
                onClick={handleSubmit}
                className="ml-2 px-4 py-2 bg-blue-500 text-white rounded-md"
            >
                Submit
            </button>
        </div>
    );
}
