// react/app/results/b/page-gemini.tsx
"use client";

import { useState } from "react";

export default function B1() {
  const [time, setTime] = useState<Date>(new Date());

  useState(() => {
    const intervalId = setInterval(() => setTime(new Date()), 1000);
    return () => clearInterval(intervalId);
  }, []);

  return (
    <div
      id="container"
      style={{
        backgroundColor: "lightgreen",
        filter: "blur(5px)", // adjust blur amount as needed
        width: "100vw", // ensure full screen width
        height: "100vh",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        gap: "4px",
      }}
    >
      <h1 className="text-xl font-bold">
        Good {time.getHours() < 12 ? "morning" : "afternoon"}
      </h1>
      <p className="text-m text-grey-700">
        {`${time.getHours()}:${String(time.getMinutes()).padStart(2, "0")}`}
      </p>
      <div className="w-[100px] h-[100px] rounded-full bg-orange-200" />
    </div>
  );
}

// sveltekit/src/routes/results/b/page-gemini.svelte
<script setup lang="ts">
    const time = new Date();
  </script>
  
  <div id="container" class="container" style="background-color: lightgreen; filter: blur(4px)">
    <h1>Good {time.getHours() < 12 ? "morning" : "afternoon"}</h1>
    <p>
      {time.getHours()}:{String(time.getMinutes()).padStart(2, "0")}
    </p>
    <div class="circle" />
  </div>
  
  <style>
    .container {
      width: 100vw;
      height: 100vh;
      padding: 1rem;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      gap: 1rem;
    }
  
    h1 {
      font-size: 1.25rem;
      line-height: 1.75rem;
      font-weight: bold;
    }
  
    p {
      font-size: 1rem;
      color: #4a5568;
    }
  
    .circle {
      width: 100px;
      height: 100px;
      border-radius: 9999px;
      background-color: rgb(254, 215, 170);
    }
  </style>
