// sveltekit/src/routes/results/a/page-gpt.svelte
<script lang="ts">
    // No need for script in this example
  </script>
  
  <div id="container" class="container">
    <h1 style="font-size: 4rem; text-align: center;">Hello</h1>
    <p style="font-size: 1rem; text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ut mauris eu magna hendrerit congue.</p>
  </div>
  
  <style>
    .container {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      width: 100%;
      height: 100%;
      padding: 0.75rem;
    }
  </style>

// react/app/results/a/page-gpt.tsx
import Head from 'next/head';

export default function A1() {
    return (
        <div id="container" className="flex justify-center items-center h-screen">
            <Head>
                <title>Next.js 14 Example</title>
            </Head>
            <div className="text-center">
                <h1 className="text-4xl">Hello</h1>
                <p className="text-base mt-4">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
            </div>
        </div>
    );
}
