// sveltekit/src/routes/results/l/page-gpt.svelte
<script setup lang="ts">
    import { onMount } from "svelte";

    let data: boolean = false;
    let isLoading: boolean = true;

    onMount(() => {
        (async () => {
            await getData();
            isLoading = false;
        })();
    });

    async function getData(): Promise<void> {
        return new Promise((resolve) => {
            setTimeout(() => {
                resolve();
                data = true;
            }, 2000);
        });
    }
</script>

<div id="container" class="container">
    {#if isLoading}
        <!-- Show spinner while loading -->
        <div class="spinner"></div>
    {:else}
        <!-- Show "API fetch complete" message when loading is complete -->
        <p>API fetch complete</p>
    {/if}
</div>

<style>
    .container {
        padding: 1rem;
        width: 100vw;
        height: 100vh;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
    }

    .spinner {
        border: 4px solid rgba(0, 0, 0, 0.1);
        border-left-color: #7983ff;
        border-radius: 50%;
        width: 50px;
        height: 50px;
        animation: spin 1s linear infinite;
    }

    @keyframes spin {
        to {
            transform: rotate(360deg);
        }
    }
</style>

// react/app/results/l/page-gpt.tsx
"use client";

import { useEffect, useState } from "react";

export default function L() {
    const [data, setData] = useState<boolean>(false);

    useEffect(() => {
        (async () => {
            await getData();
        })();
    }, []);

    async function getData(): Promise<void> {
        return new Promise((resolve) => {
            setTimeout(() => {
                resolve();
                setData(true);
            }, 2000);
        });
    }

    return (
        <div
            id="container"
            className="p-4 w-screen h-screen flex flex-col items-center justify-center"
        >
            {data ? (
                <p className="text-2xl font-bold text-center">API fetch complete</p>
            ) : (
                <div className="spinner" /> // Replace "spinner" with your spinner component
            )}
        </div>
    );
}
