// sveltekit/src/routes/results/l/page-gemini.svelte
<script setup lang="ts">
  import { onMount } from "svelte";

  let isLoading: boolean = true;
  let data: boolean = false;

  onMount(async () => {
    try {
      await getData();
    } finally {
      isLoading = false;
    }
  });

  async function getData(): Promise<void> {
    // Simulate API fetch with a delay
    await new Promise((resolve) => setTimeout(resolve, 2000));
    data = true;
  }
</script>

<div id="container" class="container">
  {#if isLoading}
    <span class="spinner">Loading...</span>
  {:else}
    <p>API fetch complete!</p>
  {/if}
</div>

<style>
  .container {
    padding: 1rem;
    width: 100vw;
    height: 100vh;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
  }

  .spinner {
    /* Add your preferred spinner styles here */
    animation: spin 1s linear infinite;
  }

  @keyframes spin {
    from {
      transform: rotate(0deg);
    }
    to {
      transform: rotate(360deg);
    }
  }
</style>

// react/app/results/l/page-gemini.tsx
"use client";

import { useEffect, useState } from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faSpinner } from "@fortawesome/free-solid-svg-icons";

export default function L() {
  const [isLoading, setIsLoading] = useState(true);
  const [data, setData] = useState(false);

  useEffect(() => {
    (async () => {
      await getData();
      setIsLoading(false);
    })();
  }, []);

  async function getData(): Promise<void> {
    return new Promise((resolve) => {
      setTimeout(() => {
        resolve();
        setData(true);
      }, 2000);
    });
  }

  return (
    <div
      id="container"
      className="p-4 w-screen h-screen flex flex-col items-center justify-center"
    >
      {isLoading ? (
        <FontAwesomeIcon icon={faSpinner} className="animate-spin mr-2" />
      ) : (
        <p>API fetch complete</p>
      )}
    </div>
  );
}
