// react/app/results/g1/page-gpt.tsx
import { useState } from 'react';

export default function G1() {
    const [value, setValue] = useState('');

    // Function to handle input change
    const handleChange = (event) => {
        const inputValue = event.target.value;
        // Check if the input value is numerical
        if (!isNaN(inputValue)) {
            // Update the state if it's numerical
            setValue(inputValue);
        }
    };

    return (
        <div id="container" className="flex justify-center items-center w-screen h-screen p-4">
            <input
                type="text"
                value={value}
                onChange={handleChange}
                className="p-2 border border-gray-300 rounded-md"
                placeholder="Enter a number"
            />
        </div>
    );
}

// sveltekit/src/routes/results/g1/page-gpt.svelte
<script>
  let inputValue = '';

  function handleInput(event) {
    const regex = /^[0-9]*$/; // Regex to allow only numerical input
    if (regex.test(event.target.value)) {
      inputValue = event.target.value;
    }
  }
</script>

<div id="container" class="container">
  <input type="text" bind:value={inputValue} on:input={handleInput} placeholder="Enter numerical value" style="text-align: center;">
</div>

<style>
  .container {
    display: flex;
    justify-content: center;
    align-items: center;
    padding: 1rem;
    width: 100vw;
    height: 100vh;
  }

  input {
    padding: 0.5rem;
    border-radius: 5px;
    border: 1px solid #ccc;
    width: 200px;
  }
</style>
