// react/app/results/g1/page-gemini.tsx
export default function G1() {
    return (
      <div id="container" className="w-screen h-screen flex justify-center items-center p-4">
        <form>
          <label htmlFor="numberInput">Enter a number:</label>
          <input
            type="number"
            id="numberInput"
            name="numberInput"
            className="border rounded px-2 py-1"
          />
        </form>
      </div>
    );
  }

// sveltekit/src/routes/results/g1/page-gemini.svelte
<script>
  let numberValue = "";

  function preventDefault(event) {
    event.preventDefault();
    // Handle the submitted number here (e.g., console.log(numberValue))
  }
</script>

<div id="container" class="container">
  <form on:submit={preventDefault}>
    <label for="numberInput">Enter a number:</label>
    <input type="number" id="numberInput" bind:value={numberValue}>
    <button type="submit">Submit</button>
  </form>
</div>


<style>
.container {
  padding: 1rem;
  width: 100vw;
  height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
}

.container form {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

</style>
