// react/app/results/g2/page-gemini.tsx
export default function G1() {
  return (
    <div id="container" className="w-screen h-screen flex justify-center items-center p-4">
      <form className="flex">  {/* Add flex class to the form */}
        <label htmlFor="numberInput">Enter a number:</label>
        <input
          type="number"
          id="numberInput"
          name="numberInput"
          className="border rounded px-2 py-1 mr-2"  {/* Add margin-right for spacing */}
        />
        <button type="submit" className="bg-blue-500 text-white px-2 py-1 rounded">Submit</button>
      </form>
    </div>
  );
}

// sveltekit/src/routes/results/g2/page-gemini.svelte
<script>
  let numberValue = "";

  function preventDefault(event) {
    event.preventDefault();
    // Handle the submitted number here (e.g., console.log(numberValue))
  }
</script>

<div id="container" class="container">
  <form on:submit={preventDefault}>
    <label for="numberInput">Enter a number:</label>
    <div style="display: flex; align-items: center;">
      <input type="number" id="numberInput" bind:value={numberValue}>
      <button type="submit">Submit</button>
    </div>
  </form>
</div>


<style>
  .container {
    padding: 1rem;
    width: 100vw;
    height: 100vh;
    display: flex;
    justify-content: center;
    align-items: center;
  }

  .container form {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
  }
</style>
