// sveltekit/src/routes/results/f2/page-gpt.svelte
<script setup lang="ts">
    let count = 0;
  
    function showAlert() {
      count++;
      alert(`You've got an email (${count})`);
    }
  </script>
  
  <div class="container">
    <button on:click={showAlert}>Click me!</button>
  </div>
  
  <style>
    .container {
      padding: 1rem;
      width: 100vw;
      height: 100vh;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
    }
  </style>

// react/app/results/f2/page-gpt.tsx
import React, { useState } from 'react';

export default function F1() {
    const [count, setCount] = useState(0);

    function showAlert() {
        alert(`You've got an email (${count} times)`);
        setCount(prevCount => prevCount + 1);
    }

    return (
        <div
            id="container"
            className="w-screen h-screen p-4 flex flex-col items-center justify-center"
        >
            <button onClick={showAlert}>Show Email Alert</button>
        </div>
    );
}
