// sveltekit/src/routes/results/f1/page-claude.svelte
<script setup lang="ts">
    function showAlert() {
        alert("You've got an email");
    }
</script>

<div class="container">
    <button on:click={showAlert}>Check Email</button>
</div>

<style>
    .container {
        padding: 1rem;
        width: 100vw;
        height: 100vh;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
    }
</style>

// react/app/results/f2/page-claude.tsx
import { useState } from 'react';

export default function F1() {
  const [count, setCount] = useState(0);

  function showAlert() {
    setCount(count + 1);
    alert(`You've got an email (${count + 1})`);
  }

  return (
    <div
      id="container"
      className="w-screen h-screen p-4 flex flex-col items-center justify-center"
    >
      <button
        onClick={showAlert}
        className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
      >
        Show Alert
      </button>
    </div>
  );
}
