// react/app/results/g3/page-gemini.tsx
import { useState } from 'react';

export default function G1() {
  const [errorMessage, setErrorMessage] = useState(''); // State to store error message

  const handleSubmit = (event) => {
    event.preventDefault(); // Prevent default form submission

    const numberInput = event.target.elements.numberInput.value;

    if (numberInput > 1000) {
      setErrorMessage('Input exceeds the maximum value');
    } else {
      setErrorMessage(''); // Clear error message if valid
      // Handle your actual form submission logic here (e.g., sending data to server)
    }
  };

  return (
    <div id="container" className="w-screen h-screen flex justify-center items-center p-4">
      <form onSubmit={handleSubmit} className="flex">
        <label htmlFor="numberInput">Enter a number:</label>
        <input
          type="number"
          id="numberInput"
          name="numberInput"
          className="border rounded px-2 py-1 mr-2"
        />
        <button type="submit" className="bg-blue-500 text-white px-2 py-1 rounded">
          Submit
        </button>
      </form>
      {errorMessage && <p className="text-red-500 text-sm mt-2">{errorMessage}</p>}
    </div>
  );
}

// sveltekit/src/routes/results/g3/page-gemini.svelte
<script>
  let numberValue = "";
  let errorMessage = "";

  function preventDefault(event) {
    event.preventDefault();
    if (numberValue < 1000) {
      errorMessage = ""; // Clear error message if input is valid
    } else {
      errorMessage = "Input exceeds the maximum value";
    }
    // Handle the submitted number here (e.g., console.log(numberValue))
  }
</script>

<div id="container" class="container">
  <form on:submit={preventDefault}>
    <label for="numberInput">Enter a number:</label>
    <div style="display: flex; align-items: center;">
      <input type="number" id="numberInput" bind:value={numberValue}>
      <button type="submit">Submit</button>
    </div>
    {#if errorMessage}
      <p style="color: red;">{errorMessage}</p>
    {/if}
  </form>
</div>


<style>
  .container {
    padding: 1rem;
    width: 100vw;
    height: 100vh;
    display: flex;
    justify-content: center;
    align-items: center;
  }

  .container form {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
  }
</style>
