// sveltekit/src/routes/results/g3/page-gpt.svelte
<script>
  import { writable } from 'svelte/store';

  let inputValue = '';
  let error = writable('');

  function handleInput(event) {
    const regex = /^[0-9]*$/; // Regex to allow only numerical input
    if (regex.test(event.target.value)) {
      inputValue = event.target.value;
      error.set('');
    } else {
      error.set('Please enter only numerical values.');
    }
  }

  function handleSubmit() {
    if (inputValue >= 1000) {
      error.set('Input exceeds the maximum value.');
    } else {
      // Handle submit logic here
      console.log("Submitted:", inputValue);
      error.set('');
    }
  }
</script>

<div id="container" class="container">
  <input type="text" bind:value={inputValue} on:input={handleInput} placeholder="Enter numerical value" style="text-align: center;">
  <button on:click={handleSubmit}>Submit</button>
  {#if $error}
    <p style="color: red; margin-top: 0.5rem;">{$error}</p>
  {/if}
</div>

<style>
  .container {
    display: flex;
    justify-content: center;
    align-items: center;
    padding: 1rem;
    width: 100vw;
    height: 100vh;
  }

  input {
    padding: 0.5rem;
    border-radius: 5px;
    border: 1px solid #ccc;
    width: 200px;
  }

  button {
    padding: 0.5rem 1rem;
    margin-left: 1rem;
    border-radius: 5px;
    border: 1px solid #007bff;
    background-color: #007bff;
    color: #fff;
    cursor: pointer;
  }
</style>

// react/app/results/g3/page-gpt.tsx
'use client';

import { useState } from 'react';

export default function G1() {
    const [value, setValue] = useState('');
    const [error, setError] = useState('');

    const handleChange = (event) => {
        const inputValue = event.target.value;
        if (!isNaN(inputValue)) {
            setValue(inputValue);
            // Clear error message when user starts typing again
            setError('');
        }
    };

    const handleSubmit = () => {
        // Parse the value to ensure it's a number
        const numericValue = parseFloat(value);
        if (numericValue >= 1000) {
            // Display error message if value exceeds 1000
            setError('Input exceeds the maximum value');
        } else {
            // Perform actions on submit
            console.log("Submitted value:", value);
        }
    };

    return (
        <div id="container" className="flex flex-col justify-center items-center w-screen h-screen p-4">
            <input
                type="text"
                value={value}
                onChange={handleChange}
                className="p-2 border border-gray-300 rounded-md mb-2"
                placeholder="Enter a number"
            />
            {error && (
                <p className="text-red-500">{error}</p>
            )}
            <button
                onClick={handleSubmit}
                className="px-4 py-2 bg-blue-500 text-white rounded-md"
            >
                Submit
            </button>
        </div>
    );
}
