// sveltekit/src/routes/results/g3/+page.svelte
<script>
    let inputValue = '';
    let errorMessage = '';
  
    function handleSubmit() {
      if (inputValue >= 1000) {
        errorMessage = 'Input exceeds the maximum value';
      } else {
        errorMessage = '';
        // Do something with the input value
        console.log('Input value:', inputValue);
      }
    }
  </script>
  
  <div id="container" class="container">
    <div class="form-container">
      <div class="input-wrapper">
        <input
          type="text"
          class="input-field"
          inputmode="numeric"
          pattern="[0-9]*"
          bind:value={inputValue}
        />
        <button class="submit-btn" on:click={handleSubmit}>Submit</button>
      </div>
      {#if errorMessage}
        <div class="error-message">{errorMessage}</div>
      {/if}
    </div>
  </div>
  
  <style>
    .container {
      padding: 1rem;
      width: 100vw;
      height: 100vh;
      display: flex;
      justify-content: center;
      align-items: center;
    }
  
    .form-container {
      text-align: center;
    }
  
    .input-wrapper {
      display: flex;
      align-items: center;
    }
  
    .input-field {
      padding: 0.5rem;
      font-size: 1rem;
      border: 1px solid #ccc;
      border-radius: 4px;
      width: 200px;
    }
  
    .submit-btn {
      margin-left: 0.5rem;
      padding: 0.5rem 1rem;
      font-size: 1rem;
      border: 1px solid #ccc;
      border-radius: 4px;
      background-color: #f0f0f0;
      cursor: pointer;
    }
  
    .error-message {
      color: red;
      margin-top: 0.5rem;
    }
  </style>

// react/app/results/g3/page.tsx
"use client";

import React, { useState } from "react";

export default function G1() {
    const [inputValue, setInputValue] = useState("");
    const [error, setError] = useState(null);

    const handleInputChange = (e) => {
        const value = e.target.value;
        setInputValue(value);

        if (value !== "" && parseInt(value) >= 1000) {
            setError("Input exceeds the maximum value");
        } else {
            setError(null);
        }
    };

    const handleSubmit = () => {
        // Add your submit logic here
        console.log("Input value:", inputValue);
    };

    return (
        <div className="w-screen h-screen p-4 flex justify-center items-center">
            <div className="flex flex-col items-center">
                <input
                    type="text"
                    pattern="\[0-9\]*"
                    className="text-center border-2 border-gray-300 rounded-md p-2"
                    placeholder="Enter numbers only"
                    value={inputValue}
                    onChange={handleInputChange}
                />
                {error && <div className="text-red-500 mt-2">{error}</div>}
                <button
                    type="button"
                    className="ml-2 px-4 py-2 bg-blue-500 text-white rounded-md mt-4"
                    onClick={handleSubmit}
                >
                    Submit
                </button>
            </div>
        </div>
    );
}
