// react/app/results/f1/page-gemini.tsx
export default function F1() {
    function showAlert() {
      alert("You've got an email");
    }
  
    return (
      <div
        id="container"
        className="w-screen h-screen p-4 flex flex-col items-center justify-center"
      >
        <button onClick={showAlert}>Check Email</button>
      </div>
    );
  }

// sveltekit/src/routes/results/f1/page-gemini.svelte
<script setup lang="ts">
    function showAlert() {
      alert("You've got an email");
    }
  </script>
  
  <div class="container">
    <button on:click={showAlert}>Check Email</button>
  </div>
  
  <style>
    .container {
      padding: 1rem;
      width: 100vw;
      height: 100vh;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
    }
  </style>
