// sveltekit/src/routes/results/b/page-gpt.svelte
<script setup lang="ts">
    const time = new Date();
</script>

<div id="container" class="container">
    <h1>Good {time.getHours() < 12 ? "morning" : "afternoon"}</h1>
    <p>
        {time.getHours()}:{String(time.getMinutes()).padStart(2, "0")}
    </p>
    <div class="circle" />
</div>

<style>
    .container {
        width: 100vw;
        height: 100vh;
        padding: 1rem;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        gap: 1rem;
        background-color: lightgreen; /* Set background color */
        backdrop-filter: blur(5px); /* Apply blur effect */
    }

    h1 {
        font-size: 1.25rem;
        line-height: 1.75rem;
        font-weight: bold;
    }

    p {
        font-size: 1rem;
        color: #4a5568;
    }

    .circle {
        width: 100px;
        height: 100px;
        border-radius: 9999px;
        background-color: rgb(254, 215, 170);
    }
</style>

// react/app/results/b/page-gpt.tsx
"use client";

import { useState } from "react";
import styles from "./styles.module.css"; // Import the CSS module

export default function B1() {
    const [time, _] = useState<Date>(new Date());

    return (
        <div
            id="container"
            className={`w-screen h-screen p-4 flex flex-col items-center justify-center gap-4 ${styles.container}`} // Apply the styles
        >
            <h1 className="text-xl font-bold">
                Good {time.getHours() < 12 ? "morning" : "afternoon"}
            </h1>
            <p className="text-m text-grey-700">{`${time.getHours()}:${String(
                time.getMinutes()
            ).padStart(2, "0")}`}</p>
            <div className="w-[100px] h-[100px] rounded-full bg-orange-200" />
        </div>
    );
}
