// react/app/results/h/page-claude.tsx
import Toast from "./Toast"

export default function H() {
    return (
        <div
            id="container"
            className="min-w-screen min-h-screen p-4 flex flex-col items-center gap-5"
        >
            <Toast />

            <section>
                <h2 className="text-2xl font-bold">Section 1</h2>
                <p className="text-m text-gray-700">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptas, magni
                    architecto laborum suscipit, voluptate doloribus, minus atque impedit nostrum
                    numquam maxime dolore! Magni expedita libero natus nobis, distinctio placeat?
                </p>
            </section>

            <section>
                <h2 className="text-2xl font-bold">Section 2</h2>
                <p className="text-m text-gray-700">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptas, magni
                    architecto laborum suscipit, voluptate doloribus, minus atque impedit nostrum
                    numquam maxime dolore! Magni expedita libero natus nobis, distinctio placeat?
                </p>
            </section>

            <section>
                <h2 className="text-2xl font-bold">Section 3</h2>
                <p className="text-m text-gray-700">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptas, magni
                    architecto laborum suscipit, voluptate doloribus, minus atque impedit nostrum
                    numquam maxime dolore! Magni expedita libero natus nobis, distinctio placeat?
                </p>
            </section>

            <section>
                <img
                    src="https://source.unsplash.com/random/800x600"
                    alt="Random"
                    className="w-full"
                />
                <h2 className="text-2xl font-bold">Section 4</h2>
                <p className="text-m text-gray-700">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptas, magni
                    architecto laborum suscipit, voluptate doloribus, minus atque impedit nostrum
                    numquam maxime dolore! Magni expedita libero natus nobis, distinctio placeat?
                </p>
            </section>

            <section>
                <h2 className="text-2xl font-bold">Section 5</h2>
                <p className="text-m text-gray-700">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptas, magni
                    architecto laborum suscipit, voluptate doloribus, minus atque impedit nostrum
                    numquam maxime dolore! Magni expedita libero natus nobis, distinctio placeat?
                </p>
            </section>

            <section>
                <h2 className="text-2xl font-bold">Section 6</h2>
                <p className="text-m text-gray-700">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptas, magni
                    architecto laborum suscipit, voluptate doloribus, minus atque impedit nostrum
                    numquam maxime dolore! Magni expedita libero natus nobis, distinctio placeat?
                </p>
            </section>

            <section>
                <h2 className="text-2xl font-bold">Section 7</h2>
                <p className="text-m text-gray-700">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptas, magni
                    architecto laborum suscipit, voluptate doloribus, minus atque impedit nostrum
                    numquam maxime dolore! Magni expedita libero natus nobis, distinctio placeat?
                </p>
            </section>

            <section>
                <h2 className="text-2xl font-bold">Section 8</h2>
                <p className="text-m text-gray-700">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptas, magni
                    architecto laborum suscipit, voluptate doloribus, minus atque impedit nostrum
                    numquam maxime dolore! Magni expedita libero natus nobis, distinctio placeat?
                </p>
            </section>

            <section>
                <h2 className="text-2xl font-bold">Section 9</h2>
                <p className="text-m text-gray-700">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptas, magni
                    architecto laborum suscipit, voluptate doloribus, minus atque impedit nostrum
                    numquam maxime dolore! Magni expedita libero natus nobis, distinctio placeat?
                </p>
            </section>

            <section>
                <h2 className="text-2xl font-bold">Section 10</h2>
                <p className="text-m text-gray-700">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptas, magni
                    architecto laborum suscipit, voluptate doloribus, minus atque impedit nostrum
                    numquam maxime dolore! Magni expedita libero natus nobis, distinctio placeat?
                </p>

                <img
                    src="https://source.unsplash.com/random/800x600"
                    alt="Random"
                    className="w-full"
                />
            </section>

            <section>
                <h2 className="text-2xl font-bold">Section 11</h2>
                <p className="text-m text-gray-700">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptas, magni
                    architecto laborum suscipit, voluptate doloribus, minus atque impedit nostrum
                    numquam maxime dolore! Magni expedita libero natus nobis, distinctio placeat?
                </p>
            </section>

            <section>
                <h2 className="text-2xl font-bold">Section 12</h2>
                <p className="text-m text-gray-700">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptas, magni
                    architecto laborum suscipit, voluptate doloribus, minus atque impedit nostrum
                    numquam maxime dolore! Magni expedita libero natus nobis, distinctio placeat?
                </p>

                <img
                    src="https://source.unsplash.com/random/800x600"
                    alt="Random"
                    className="w-full"
                />
            </section>

            <section>
                <h2 className="text-2xl font-bold">Section 13</h2>
                <p className="text-m text-gray-700">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptas, magni
                    architecto laborum suscipit, voluptate doloribus, minus atque impedit nostrum
                    numquam maxime dolore! Magni expedita libero natus nobis, distinctio placeat?
                </p>
            </section>

            <section>
                <h2 className="text-2xl font-bold">Section 14</h2>
                <p className="text-m text-gray-700">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptas, magni
                    architecto laborum suscipit, voluptate doloribus, minus atque impedit nostrum
                    numquam maxime dolore! Magni expedita libero natus nobis, distinctio placeat?
                </p>

                <img
                    src="https://source.unsplash.com/random/800x600"
                    alt="Random"
                    className="w-full"
                />
            </section>

            <section>
                <h2 className="text-2xl font-bold">Section 15</h2>
                <p className="text-m text-gray-700">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptas, magni
                    architecto laborum suscipit, voluptate doloribus, minus atque impedit nostrum
                    numquam maxime dolore! Magni expedita libero natus nobis, distinctio placeat?
                </p>
            </section>
        </div>
    );
}

// sveltekit/src/routes/results/h/page-claude.svelte
<script>
  import Toast from './ToastClaude.svelte';
  import { onMount } from 'svelte';

  let showToast = false;

  onMount(() => {
      const handleScroll = () => {
          const scrollHeight = document.documentElement.scrollHeight;
          const scrollTop = document.documentElement.scrollTop;
          const clientHeight = document.documentElement.clientHeight;

          if (scrollTop + clientHeight >= scrollHeight && !showToast) {
              showToast = true;
          }
      };

      window.addEventListener('scroll', handleScroll);

      return () => {
          window.removeEventListener('scroll', handleScroll);
      };
  });
</script>

<div id="container" class="container">
  <section>
      <h2>Section 1</h2>
      <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptas, magni
          architecto laborum suscipit, voluptate doloribus, minus atque impedit nostrum numquam
          maxime dolore! Magni expedita libero natus nobis, distinctio placeat?
      </p>
  </section>

  <section>
      <h2>Section 2</h2>
      <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptas, magni
          architecto laborum suscipit, voluptate doloribus, minus atque impedit nostrum numquam
          maxime dolore! Magni expedita libero natus nobis, distinctio placeat?
      </p>
  </section>

  <section>
      <h2>Section 3</h2>
      <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptas, magni
          architecto laborum suscipit, voluptate doloribus, minus atque impedit nostrum numquam
          maxime dolore! Magni expedita libero natus nobis, distinctio placeat?
      </p>
  </section>

  <section>
      <img src="https://source.unsplash.com/random/800x600" alt="Random" />
      <h2>Section 4</h2>
      <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptas, magni
          architecto laborum suscipit, voluptate doloribus, minus atque impedit nostrum numquam
          maxime dolore! Magni expedita libero natus nobis, distinctio placeat?
      </p>
  </section>

  <section>
      <h2>Section 5</h2>
      <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptas, magni
          architecto laborum suscipit, voluptate doloribus, minus atque impedit nostrum numquam
          maxime dolore! Magni expedita libero natus nobis, distinctio placeat?
      </p>
  </section>

  <section>
      <h2>Section 6</h2>
      <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptas, magni
          architecto laborum suscipit, voluptate doloribus, minus atque impedit nostrum numquam
          maxime dolore! Magni expedita libero natus nobis, distinctio placeat?
      </p>
  </section>

  <section>
      <h2>Section 7</h2>
      <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptas, magni
          architecto laborum suscipit, voluptate doloribus, minus atque impedit nostrum numquam
          maxime dolore! Magni expedita libero natus nobis, distinctio placeat?
      </p>
  </section>

  <section>
      <h2>Section 8</h2>
      <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptas, magni
          architecto laborum suscipit, voluptate doloribus, minus atque impedit nostrum numquam
          maxime dolore! Magni expedita libero natus nobis, distinctio placeat?
      </p>
  </section>

  <section>
      <h2>Section 9</h2>
      <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptas, magni
          architecto laborum suscipit, voluptate doloribus, minus atque impedit nostrum numquam
          maxime dolore! Magni expedita libero natus nobis, distinctio placeat?
      </p>
  </section>

  <section>
      <h2>Section 10</h2>
      <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptas, magni
          architecto laborum suscipit, voluptate doloribus, minus atque impedit nostrum numquam
          maxime dolore! Magni expedita libero natus nobis, distinctio placeat?
      </p>

      <img src="https://source.unsplash.com/random/800x600" alt="Random" />
  </section>

  <section>
      <h2>Section 11</h2>
      <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptas, magni
          architecto laborum suscipit, voluptate doloribus, minus atque impedit nostrum numquam
          maxime dolore! Magni expedita libero natus nobis, distinctio placeat?
      </p>
  </section>

  <section>
      <h2>Section 12</h2>
      <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptas, magni
          architecto laborum suscipit, voluptate doloribus, minus atque impedit nostrum numquam
          maxime dolore! Magni expedita libero natus nobis, distinctio placeat?
      </p>

      <img src="https://source.unsplash.com/random/800x600" alt="Random" />
  </section>

  <section>
      <h2>Section 13</h2>
      <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptas, magni
          architecto laborum suscipit, voluptate doloribus, minus atque impedit nostrum numquam
          maxime dolore! Magni expedita libero natus nobis, distinctio placeat?
      </p>
  </section>

  <section>
      <h2>Section 14</h2>
      <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptas, magni
          architecto laborum suscipit, voluptate doloribus, minus atque impedit nostrum numquam
          maxime dolore! Magni expedita libero natus nobis, distinctio placeat?
      </p>

      <img src="https://source.unsplash.com/random/800x600" alt="Random" />
  </section>

  <section>
      <h2>Section 15</h2>
      <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptas, magni
          architecto laborum suscipit, voluptate doloribus, minus atque impedit nostrum numquam
          maxime dolore! Magni expedita libero natus nobis, distinctio placeat?
      </p>
  </section>

  {#if showToast}
    <Toast />
{/if}
</div>

<style>
  .container {
      padding: 1rem;
      min-width: 100vw;
      min-height: 100vh;
      display: flex;
      flex-direction: column;
      align-items: center;
      gap: 1.25rem;
  }

  h2 {
      font-size: 1.5rem;
      line-height: 2rem;
      font-weight: bold;
  }

  p {
      font-size: 1rem;
      color: #4a5568;
  }

  img {
      width: 100%;
  }
</style>
